<?php

use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Split\Algorithms\WeightedSample;

class WeightedSampleTest extends TestCase {
    /* @var WeightedSample */
    protected $algo;

    public function setUp() {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->algo = new WeightedSample();
    }

    public function tearDown() {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }


    public function test_should_always_return_a_heavily_weighted_option() {
        //TODO: replace with real experiments
        $experiment = (object)[
            'alternatives' => [
                (object)["weight" => 0, 'name' => 'one'],
                (object)["weight" => 0, 'name' => 'two'],
                (object)["weight" => 100, 'name' => 'three'],
            ],
        ];
        $this->assertEquals((object)["weight" => 100, 'name' => 'three'], $this->algo->choose_alternative($experiment));
    }


    public function test_rand_between_0_and_1() {
        $rand = $this->algo->random_01();
        $this->assertGreaterThanOrEqual(0, $rand);
        $this->assertLessThanOrEqual(1, $rand);
    }

    public function test_should_return_an_alternative() {
        //TODO
    }

    public function test_should_return_one_of_the_results() {
        //TODO: replace with real experiments
        $experiment = (object)[
            'alternatives' => [
                (object)["weight" => 1, 'name' => 'one'],
                (object)["weight" => 1, 'name' => 'two'],
            ],
        ];
        $this->assertContains($this->algo->choose_alternative($experiment)->name,['one','two']);
    }


}
